#!/bin/sh
# AKA-00 startup — called by aka-server or directly
# cd to project dir first, or set AKA_HOME

AKA_HOME="${AKA_HOME:-$HOME/AKA-00}"
LOCK_FILE="/tmp/aka-ota-lock"

# Prevent duplicate instances (e.g. S99webstart + manual run)
PID_FILE="/var/run/aka-init.pid"
if [ -f "$PID_FILE" ]; then
    _old=$(cat "$PID_FILE")
    if kill -0 "$_old" 2>/dev/null; then
        echo "[init] already running (pid $_old), exiting"
        exit 0
    fi
fi
echo $$ > "$PID_FILE"

chmod +x "$AKA_HOME/uart_init.sh" 2>/dev/null || true
"$AKA_HOME/uart_init.sh"

# SSL cert auto-generated by run.py, skipping https_init.sh

# Self-respawn loop: if Python crashes, restart it.
# If OTA is in progress, wait for it to finish before starting.
while true; do
    while [ -f "$LOCK_FILE" ]; do
        sleep 0.5
    done
    python3 "$AKA_HOME/run.py"
    echo "[init] Python exited, restarting in 2s..."
    sleep 2
done
